site_name: Password Safe Documentation
site_author: MATESO GmbH
repo_url: https://github.com/PasswordSafe/pws-docs
repo_name: PasswordSafe/pws-docs
edit_uri: edit/main/docs/

extra:
  generator: true
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
    cookies:
      analytics: Analytics & Feedback
  analytics:
    provider: google
    property: G-QY3E27F64E
    feedback:
        title: Was this page helpful?
        ratings:
          - icon: material/emoticon-happy-outline
            name: This page was helpful
            data: 1
            note: >-
              Thanks for your feedback!
          - icon: material/emoticon-sad-outline
            name: This page could be improved
            data: 0
            note: >-
              Thanks for your feedback!
  social:
  - icon: fontawesome/brands/linkedin
    name: MATESO GmbH on LinkedIn
    link: https://www.linkedin.com/company/mateso-gmbh/
  - icon: fontawesome/brands/twitter
    name: MATESO GmbH on Twitter
    link: https://twitter.com/matesogmbh

theme:
  logo: assets/logo_white.png
  favicon: assets/favicon.svg
  language: en
  name: material
  icon:
    repo: material/file-document-outline
  features:
  - navigation.indexes
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.instant
  - navigation.top
  - search.highlight
  - search.suggest
  - header.autohide
  - toc.autohide
  - content.tabs.link
  - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/js/newtab.js

plugins:
  - search:
      prebuild_index: true
  - git-revision-date-localized:
      type: timeago
      custom_format: "%d. %B %Y"
      timezone: Europe/Berlin
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
          - index.md
      enabled: !ENV [CI, false]
  - awesome-pages
  - macros:
      on_error_fail: !ENV [CI, false]
      include_yaml:
        - macros.yml
  - glightbox
  - tags

markdown_extensions:
  - meta
  - abbr
  - admonition
  - footnotes
  - tables
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: ⚓︎
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: 'docs/'
      check_paths: true
      url_download: false
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

copyright: Maintained with ❤️ by <a href='https://www.passwordsafe.com' target='_blank'>MATESO GmbH</a> and <a href='/contribute/#contributors'>contributors</a>! –
  <a href="#__consent">Change cookie settings</a>
