name: Check links with linkcheck

on:
  schedule:
    # Run every monday at 06:00 AM
    - cron: '0 6 * * 1'

  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Check links
      uses: filiph/linkcheck@2.0.23
      with:
        arguments: https://docs.passwordsafe.com #--show-redirects --external